### PR TITLE
Collating seqkit statistics files into a single file

### PR DESCRIPTION
**Pull request by y-popov**
https://jira.sanger.ac.uk/browse/CASMRD-36

### CODE REVIEW

**Comment by y-popov** [comment]
There are two topics to discuss

1. Currently code uses `meta.id` as sample ID. This value changes between stages. Shoud we use another source of sample ID?
2. Pipeline outputs resulting file into `params.outdir`. Do we want to change this as well as a filename?

**Comment by vaofford** [comment]
> There are two topics to discuss
> 
> 1. Currently code uses `meta.id` as sample ID. This value changes between stages. Shoud we use another source of sample ID?
> 2. Pipeline outputs resulting file into `params.outdir`. Do we want to change this as well as a filename?

1. Interesting - agree, there should be a consistent reference for the sample ID are we able to map out what each process is using to get the sample ID to look at the best place to source it consistently?
2. Should be OK to go into the same directory - in addition, we'd want to start moving to a production mode where we don't publish the intermediate/individual files

**Comment by vaofford** [comment]
Added small tweak to write the collated seqkit stats file to the seqkit_stats subdirectory. If you're happy with that, all tests ran ok and we can merge?

**Comment by y-popov** [comment]
Yeap, I am. Seems we are ready to merge this

**Pull request merged**
