### PR TITLE
Cutadapt jsons collation

### PR DESCRIPTION
**Pull request by y-popov**
https://jira.sanger.ac.uk/browse/CASMRD-158

### CODE REVIEW

**Comment by vaofford** [comment]
@y-popov this could be in the 100s if Jamie is using it for plasmid quantification in production with multiple libraries enabled.  How much effort would it be to take the current collation code and spawn it as a new process? Sounds safer.

**Comment by y-popov** [comment]
The max json size in tests is 30k. Even for 1000 files we will have:
30k * 2 (adapter + primer) * 1000 (# of files) * 2 (code creates a copy) = 118Mb
So most likely it will fit into main process' memory that is usually around 4Gb.

However I agree, it is safer to use a separate process. I've just found [a nice way](https://www.nextflow.io/docs/latest/process.html#native-execution) to execute groovy code inside a process as I was not enthusiastic to use python (think container) for just json parsing. Since there is no need to rewrite code it won't take long

**Comment by y-popov** [comment]
It turned out that nextflow can execute native processes (groovy code) only using `local` executor. This means nextflow won't ask for more resources (RAM). However it will launch a new thread and make execution in parallel.

I still was reluctant to use a container and tried JsonBuilder and StreamingJsonBuilder in order not to store the content of all jsons in memory, without success though. I ended up writing quite a dumb but memory efficient way of writing final json line by line per sample.

**Comment by vaofford** [comment]
@y-popov am getting a related warning:
```
WARN: Process 'NFCORE_QUANTS:SGE:COLLATE_CUTADAPT_JSONS' cannot be executed by 'lsf' executor -- Using 'local' executor instead
```

**Pull request merged**
